// vue/lib/components/navbar/examples/nav-in-center.vue
<template>
  <e-navbar class="px-lg-4" :title="'TITLE'" nav-in-center>
    <div slot="brand">
      <a class="e-logo mx-4" href="" @click.prevent>
        <span>Elements <small>stay simple</small></span>
      </a>
    </div>
    <div slot="collapse">
      <ul class="navbar-nav pt-3 pt-md-0">
        <li class="nav-item active">
          <a class="nav-link" href="" @click.prevent>Overview</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="" @click.prevent>Bootstrap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="" @click.prevent>Pages</a>
        </li>
      </ul>
    </div>
    <div slot="actions">
      <button class="btn btn-success" type="button">
        <i class="fa fa-user-circle"></i>
        <span class="d-none d-md-inline-block">Morty Smith</span>
      </button>
    </div>
  </e-navbar>
</template>

<script>
  import ENavbar from '../index'

  export default {
    components: { ENavbar }
  }
</script>

// react/lib/components/navbar/examples/NavInCenter.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ENavbar from '../index'
import { Nav, NavItem, NavLink } from 'reactstrap'

const Brand = () => (
  <a className="e-logo mx-4" href="" onClick={(e) => e.preventDefault()}>
    <span>Elements <small>stay simple</small></span>
  </a>
)

const CollapseNav = () => (
  <div className="d-md-flex">
    <Nav className="navbar-nav mr-auto py-3 py-md-0">
      <NavItem>
        <NavLink className="active" href="" onClick={(e) => e.preventDefault()}>Overview</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="" onClick={(e) => e.preventDefault()}>Bootstrap</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="" onClick={(e) => e.preventDefault()}>Pages</NavLink>
      </NavItem>
    </Nav>
  </div>
)

const Actions = () => (
  <button className="btn btn-success" type="button">
    <i className="fa fa-user-circle"></i>
    <span className="d-none d-md-inline-block">Morty Smith</span>
  </button>
)

const propTypes = {
  className: PropTypes.string
}

class ENavbarNavInCenter extends Component {
  render() {
    return (
      <ENavbar
        title="TITLE"
        brandNode={<Brand/>}
        collapseNode={<CollapseNav/>}
        actionsNode={<Actions/>}
        className={this.props.className}
        navInCenter/>
    );
  }
}

ENavbarNavInCenter.propTypes = propTypes

export default ENavbarNavInCenter
