// vue/demo/lib/elements/components/navbar/examples/brand-in-center.vue
<template>
  <e-navbar class="px-lg-4" :title="'TITLE'" brand-in-center>
    <div slot="brand">
      <a class="e-logo mx-4 my-2" href="" @click.prevent>
        <span>Elements <small>stay simple</small></span>
      </a>
    </div>
    <div slot="collapse">
      <ul class="navbar-nav pt-3 pt-md-0">
        <li class="nav-item active">
          <a class="nav-link" href="" @click.prevent>Overview</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="" @click.prevent>Bootstrap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="" @click.prevent>Pages</a>
        </li>
      </ul>
    </div>
    <div slot="actions">
      <form class="form-inline">
        <div class="input-with-ico">
          <i class="input-ico fa fa-fw fa-search"></i>
          <input class="form-control form-control-rounded" type="search" placeholder="Search" style="max-width: 170px">
        </div>
      </form>
    </div>
  </e-navbar>
</template>

<script>
  import ENavbar from '../index'

  export default {
    components: { ENavbar }
  }
</script>

// react/testing/src/elements/components/navbar/examples/BrandInCenter.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ENavbar from '../index'
import { Nav, NavItem, NavLink } from 'reactstrap'

const Brand = () => (
  <a className="e-logo mx-4 my-2" href="" onClick={(e) => e.preventDefault()}>
    <span>Elements <small>stay simple</small></span>
  </a>
)

const CollapseNav = () => (
  <div className="d-md-flex">
    <Nav className="navbar-nav mr-auto py-3 py-md-0">
      <NavItem>
        <NavLink className="active" href="" onClick={(e) => e.preventDefault()}>Overview</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="" onClick={(e) => e.preventDefault()}>Bootstrap</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="" onClick={(e) => e.preventDefault()}>Pages</NavLink>
      </NavItem>
    </Nav>
  </div>
)

const Actions = () => {
  const inputStyle = {
    maxWidth: '170px'
  }
  return (
    <form className="form-inline">
      <div className="input-with-ico">
        <i className="input-ico fa fa-fw fa-search"></i>
        <input className="form-control form-control-rounded" type="search" placeholder="Search" style={inputStyle}/>
      </div>
    </form>
  )
}

const propTypes = {
  className: PropTypes.string
}

class ENavbarBrandInCenter extends Component {
  render() {
    return (
      <ENavbar
        title="TITLE"
        brandNode={<Brand/>}
        collapseNode={<CollapseNav/>}
        actionsNode={<Actions/>}
        className={this.props.className}
        brandInCenter/>
    );
  }
}

ENavbarBrandInCenter.propTypes = propTypes

export default ENavbarBrandInCenter
