// vue/testing/lib/elements/components/panel/examples/custom-head.vue
<template>
  <e-panel>
    <template slot="head">
      <div class="h6 font-weight-bold text-center">Custom Head</div>
      <hr>
    </template>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </e-panel>
</template>

<script>
  import EPanel from '../index'

  export default {
    components: { EPanel }
  }
</script>

// react/lib/components/panel/examples/CustomHead.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import EPanel from '../index'

const propTypes = {
  className: PropTypes.string
}

class EPanelCustomHead extends Component {
  render() {
    const Head = () => (
      <div>
        <div className="h6 font-weight-bold text-center">Custom Head</div>
        <hr/>
      </div>
    )

    return (
      <EPanel headNode={<Head/>}>
        <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card content.</p>
      </EPanel>
    )
  }
}

EPanelCustomHead.propTypes = propTypes

export default EPanelCustomHead
