// react/example/src/elements/components/panel/examples/Actions.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import EPanel from '../index'

const propTypes = {
  className: PropTypes.string
}

class EPanelActions extends Component {
  render() {
    const Actions = () => (
      <i className="fa fa-fw fa-edit"></i>
    )

    return (
      <EPanel title="Panel Actions" actionsNode={<Actions/>}>
        <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card content.</p>
      </EPanel>
    )
  }
}

EPanelActions.propTypes = propTypes

export default EPanelActions

// vue/demo/lib/elements/components/panel/examples/actions.vue
<template>
  <e-panel title="Panel Actions">
    <template slot="actions">
      <i class="fa fa-fw fa-edit"></i>
    </template>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </e-panel>
</template>

<script>
  import EPanel from '../index'

  export default {
    components: { EPanel }
  }
</script>
