// vue/demo/lib/elements/components/chart/examples/area.vue
<template>
  <e-line-chart
    :chartData="data"
    :height="height"
    :options="options"></e-line-chart>
</template>

<script>
  import ELineChart from '../types/line'
  import { colors } from '../options'

  export default {
    components: { ELineChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed', 'Thu'],
          datasets: [
            {
              label: 'Area',
              borderColor: '#ffffff',
              borderWidth: 2,
              backgroundColor: colors.green.fade(0.2).string(),
              pointRadius: 3,
              data: [3, 12, 3, 12]
            },
          ]
        },
        options: {
          scales: {
            yAxes: [
              {
                ticks: {
                  beginAtZero: true
                }
              }
            ],
          },
        }
      }
    }
  }
</script>

// react/testing/src/elements/components/chart/examples/Area.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class EAreaChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true
            }
          }
        ],
      },
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed', 'Thu'],
        datasets: [
          {
            label: 'Area',
            borderColor: '#ffffff',
            borderWidth: 2,
            backgroundColor: colors.green.alpha(0.6).string(),
            pointRadius: 3,
            data: [3, 12, 3, 12]
          },
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="line" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default EAreaChart
