// angular/lib/components/chart/examples/area/area.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import colors from '../../colors'

@Component({
  selector: 'chart-area',
  encapsulation: ViewEncapsulation.None,
  template: `
    <e-chart type="line" [options]="options" [data]="data" [height]="height"></e-chart>
  `
})
export class ChartAreaComponent implements OnInit {

  public options: any = {
    scales: {
      yAxes: [
        {
          ticks: {
            beginAtZero: true
          }
        }
      ],
      xAxes: []
    },
  }

  @Input() height: number;

  public data: any = {
    labels: ['Mon', 'Tue', 'Wed', 'Thu'],
    datasets: [
      {
        label: 'Area',
        borderColor: '#ffffff',
        borderWidth: 2,
        backgroundColor: colors.green.alpha(0.6).string(),
        pointRadius: 3,
        data: [3, 12, 3, 12]
      },
    ]
  }

  constructor() { }

  ngOnInit() {
  }

}

// react/testing/src/elements/components/chart/examples/Area.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class EAreaChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true
            }
          }
        ],
      },
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed', 'Thu'],
        datasets: [
          {
            label: 'Area',
            borderColor: '#ffffff',
            borderWidth: 2,
            backgroundColor: colors.green.alpha(0.6).string(),
            pointRadius: 3,
            data: [3, 12, 3, 12]
          },
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="line" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default EAreaChart
