// vue/demo/lib/elements/components/chart/examples/bar.vue
<template>
  <e-bar-chart
    :chartData="data"
    :height="height"
    :options="options"></e-bar-chart>
</template>

<script>
  import EBarChart from '../types/bar'
  import { colors } from '../options'

  export default {
    components: { EBarChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed'],
          datasets: [
            {
              label: 'Bar',
              backgroundColor: colors.green.string(),
              borderColor: '#ffffff',
              data: [7, 10, 13]
            }
          ]
        },
        options: {
          scales: {
            yAxes: [
              {
                ticks: {
                  beginAtZero: true
                }
              }
            ],
            xAxes: [
              {
                categoryPercentage: 0.6,
                barPercentage: 0.4,
              }
            ]
          },
        }
      }
    }
  }
</script>

// react/testing/src/elements/components/chart/examples/Bar.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class EBarChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true
            }
          }
        ],
        xAxes: [
          {
            categoryPercentage: 0.6,
            barPercentage: 0.4,
          }
        ]
      },
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed'],
        datasets: [
          {
            label: 'Bar',
            backgroundColor: colors.green.string(),
            borderColor: '#ffffff',
            data: [7, 10, 13]
          }
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="bar" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default EBarChart
