// vue/example/lib/elements/components/chart/examples/donut.vue
<template>
  <e-donut-chart
    :chartData="data"
    :options="options"
    :height="height"></e-donut-chart>
</template>

<script>
  import EDonutChart from '../types/donut'
  import { colors } from '../options'

  export default {
    components: { EDonutChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed'],
          datasets: [
            {
              label: 'Donut',
              backgroundColor: colors.array(),
              hoverBorderColor: '#fff',
              data: [5, 10, 8]
            }
          ]
        },
        options: {
          legend: {
            position: 'bottom',
            labels: {
              usePointStyle: true,
              padding: 20
            }
          }
        }
      }
    }
  }
</script>

// react/testing/src/elements/components/chart/examples/Donut.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class EDonutChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      legend: {
        position: 'bottom',
        labels: {
          usePointStyle: true,
          padding: 20
        }
      }
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed'],
        datasets: [
          {
            label: 'Donut',
            backgroundColor: colors.array(),
            hoverBorderColor: '#fff',
            data: [5, 10, 8]
          }
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="doughnut" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default EDonutChart
