// vue/demo/src/vue/pages/charts/DonutChart.vue
<template>
  <e-donut-chart
    :chartData="chartData"
    :options="options"
    :height="height"></e-donut-chart>
</template>

<script>
  import EDonutChart from 'elements/chart/types/donut'
  import { colors } from 'elements/chart/options'

  export default {
    components: { EDonutChart },
    props: {
      height: Number
    },
    data: function() {
      return {
        chartData: {
          labels: ['Angular', 'Vue', 'React'],
          datasets: [
            {
              backgroundColor: colors.array(),
              hoverBorderColor: 'white',
              data: [35, 35, 35]
            }
          ]
        },
        options: {
          legend: {
            position: 'bottom',
            labels: {
              usePointStyle: true,
              padding: 20
            }
          }
        }
      }
    }
  }
</script>

// react/testing/src/components/pages/charts/DonutChart.js
import React, { Component } from 'react'
import EChart from '../../../elements/components/chart'
import { colors } from '../../../elements/components/chart/options'

class DonutChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      legend: {
        position: 'bottom',
        labels: {
          usePointStyle: true,
          padding: 20
        }
      }
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed'],
        datasets: [
          {
            label: 'Donut',
            backgroundColor: colors.array(),
            hoverBorderColor: '#fff',
            data: [5, 10, 8]
          }
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="doughnut" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default DonutChart
