// vue/demo/src/vue/Bootstrap.vue
<template>
  <div class="e-content">
    <iframe
      id="k-sink"
      class="border-0 w-100 align-top"
      title="Bootstrap 4 Kitchen Sink"
      src="../../../k-sink.html"
      ref="iframe"
      @load="setIFrameHeight"
      :style="{ minHeight: '101vh', overflow: 'hidden' }" />
  </div>
</template>

<script>
  export default {
    data: function() {
      return {}
    },
    created: function() {
      window.parent.addEventListener('resize', this.setIFrameHeight)
    },
    methods: {
      setIFrameHeight: function() {
        const iframe = this.$refs.iframe
        const parent = window.parent
        if (iframe) {
          iframe.height = ""
          const doc = iframe.contentDocument ? iframe.contentDocument : iframe.contentWindow.document
          const height = Math.max( doc.body.scrollHeight, doc.body.offsetHeight, doc.documentElement.clientHeight, doc.documentElement.scrollHeight, doc.documentElement.offsetHeight )
          iframe.height = height + "px"
          if (parent.setDemoFrameHeight) {
            parent.setDemoFrameHeight()
          }
        }
      }
    },
    beforeDestroy: function() {
      window.parent.removeEventListener('resize', this.setIFrameHeight)
    }
  }
</script>

// react/demo/src/components/Bootstrap.js
/* eslint-disable no-restricted-globals */
import React, { Component } from 'react'

class Bootstrap extends Component {
  constructor(props) {
    super(props)
    this.iframe = null
    this.setIFrameHeight = this.setIFrameHeight.bind(this)
  }

  componentDidMount() {
    window.parent.addEventListener('resize', this.setIFrameHeight)
  }

  componentWillUnmount() {
    window.parent.removeEventListener('resize', this.setIFrameHeight)
  }

  setIFrameHeight() {
    if (this.iframe) {
      const iframe = this.iframe;
      const parent = window.parent;
      if (iframe) {
        iframe.height = ""
        const doc = iframe.contentDocument ? iframe.contentDocument : iframe.contentWindow.document
        const height = Math.max( doc.body.scrollHeight, doc.body.offsetHeight )
        this.iframe.height = height + "px"
        if (parent.setDemoFrameHeight) {
          parent.setDemoFrameHeight()
        }
      }
    }
  }

  render() {
    return (
      <div className="e-content">
        <iframe
          id="k-sink"
          className="border-0 w-100 align-top"
          title="Bootstrap 4 Kitchen Sink"
          src="../../../k-sink.html"
          ref={(iframe) => this.iframe = iframe}
          onLoad={this.setIFrameHeight}
          style={{ minHeight: '101vh', overflow: 'hidden' }} />
      </div>
    )
  }
}

export default Bootstrap
