// react/lib/components/chart/examples/Line.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class ELineChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true
            }
          }
        ],
      },
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed', 'Thu'],
        datasets: [
          {
            label: 'Line',
            borderColor: colors.green.string(),
            backgroundColor: 'transparent',
            data: [3, 12, 3, 12]
          }
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="line" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default ELineChart

// vue/testing/lib/elements/components/chart/examples/line.vue
<template>
  <e-line-chart
    :chartData="data"
    :height="height"
    :options="options"></e-line-chart>
</template>

<script>
  import ELineChart from '../types/line'
  import { colors } from '../options'

  export default {
    components: { ELineChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed', 'Thu'],
          datasets: [
            {
              label: 'Line',
              borderColor: colors.green.string(),
              backgroundColor: 'transparent',
              data: [3, 12, 3, 12]
            }
          ]
        },
        options: {
          scales: {
            yAxes: [
              {
                ticks: {
                  beginAtZero: true
                }
              }
            ],
          },
        }
      }
    }
  }
</script>
