// vue/lib/components/panel/examples/default.vue
<template>
  <e-panel title="Title" subtitle="Subtitle">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </e-panel>
</template>

<script>
  import EPanel from '../index'

  export default {
    components: { EPanel }
  }
</script>

// react/testing/src/elements/components/panel/examples/Default.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import EPanel from '../index'

const propTypes = {
  className: PropTypes.string
}

class EPanelDefault extends Component {
  render() {
    return (
      <EPanel title="Title" subtitle="Subtitle">
        <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card''s content.</p>
      </EPanel>
    )
  }
}

EPanelDefault.propTypes = propTypes

export default EPanelDefault
