// react/testing/src/elements/components/datepicker/examples/Addons.js
import React, { Component } from 'react'
import EDatepickerAddons from '../types/addons'

class EAddonsPicker extends Component {
  constructor(props) {
    super(props)
    this.state = {
      date: new Date()
    }
    this.handleDateChange = this.handleDateChange.bind(this)
  }

  handleDateChange(value) {
    this.setState({
      date: value
    })
  }

  render() {
    return (
      <EDatepickerAddons 
        value={this.state.date}
        onChange={this.handleDateChange}
        prepend="fa fa-fw fa-calendar"
        placeholder="Addons"
        clear />
    )
  }
}

export default EAddonsPicker

// vue/lib/components/datepicker/examples/addons.vue
<template>
  <e-datepicker-addons
    :value.sync="date"
    prepend="fa fa-fw fa-calendar"
    clear
    placeholder="Addons"></e-datepicker-addons>
</template>

<script>
  import EDatepickerAddons from '../types/addons'

  export default {
    components: { EDatepickerAddons },
    data: function() {
      return {
        date: new Date()
      }
    }
  }
</script>
