// react/example/src/elements/components/datepicker/examples/Range.js
import React, { Component } from 'react'
import EDatepickerRange from '../types/range'

class ERangePicker extends Component {
  constructor(props) {
    super(props)
    this.state = {
      date: []
    }
    this.handleDateChange = this.handleDateChange.bind(this)
  }

  handleDateChange(value) {
    this.setState({
      date: value
    })
  }

  render() {
    return (
      <EDatepickerRange value={this.state.date} onChange={this.handleDateChange} placeholder="Range" />
    )
  }
}

export default ERangePicker

// vue/lib/components/datepicker/examples/range.vue
<template>
  <e-datepicker-range :value.sync="dates" placeholder="Range"></e-datepicker-range>
</template>

<script>
  import EDatepickerRange from '../types/range'

  export default {
    components: { EDatepickerRange },
    data: function() {
      return {
        dates: []
      }
    }
  }
</script>
