// angular/example/src/elements/components/navlist/examples/active-bg/active-bg.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'navlist-active-bg',
  templateUrl: './active-bg.component.html',
  encapsulation: ViewEncapsulation.None
})
export class NavlistActiveBgComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<e-navlist activeBg={{true}}>
  <ul class="nav">
    <li class="nav-item">
      <a href="" class="nav-link" (click)="$event.preventDefault()">
        <i class="fa fa-fw fa-home mr-1"></i>
        <span>Home</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="" class="nav-link" (click)="$event.preventDefault()">
        <i class="fa fa-fw fa-bookmark mr-1"></i>
        <span>Bookmarks</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="" class="nav-link" (click)="$event.preventDefault()">
        <i class="fa fa-fw fa-envelope mr-1"></i>
        <span>Messages</span>
        <span class="badge badge-light ml-1">4</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="" class="nav-link" (click)="$event.preventDefault()">
        <i class="fa fa-fw fa-cog mr-1"></i>
        <span>Settings</span>
      </a>
    </li>
  </ul>
</e-navlist>

// react/demo/src/elements/components/navlist/examples/ActiveBg.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ENavlist from '../index'
import { Nav, NavItem, NavLink } from 'reactstrap'

const propTypes = {
  className: PropTypes.string
}

class ENavlistActiveBg extends Component {
  render() {
    return (
      <div className="card p-3">
        <ENavlist activeBg>
          <Nav>
            <NavItem>
              <NavLink className="active" href="" onClick={(e) => e.preventDefault()}>
                <i className="fa fa-fw fa-home mr-1"></i>
                <span>Home</span>
              </NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>
                <i className="fa fa-fw fa-bookmark mr-1"></i>
                <span>Bookmarks</span>
              </NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>
                <i className="fa fa-fw fa-envelope mr-1"></i>
                <span>Messages</span>
                <span className="badge badge-light ml-1">4</span>
              </NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>
                <i className="fa fa-fw fa-cog mr-1"></i>
                <span>Settings</span>
              </NavLink>
            </NavItem>
          </Nav>
        </ENavlist>
      </div>
    );
  }
}

ENavlistActiveBg.propTypes = propTypes

export default ENavlistActiveBg
