// vue/demo/src/vue/Bootstrap.vue
<template>
  <div class="e-content">
    <iframe
      id="k-sink"
      class="border-0 w-100 align-top"
      title="Bootstrap 4 Kitchen Sink"
      src="../../../k-sink.html"
      ref="iframe"
      @load="setIFrameHeight"
      :style="{ minHeight: '101vh', overflow: 'hidden' }" />
  </div>
</template>

<script>
  export default {
    data: function() {
      return {}
    },
    created: function() {
      window.parent.addEventListener('resize', this.setIFrameHeight)
    },
    methods: {
      setIFrameHeight: function() {
        const iframe = this.$refs.iframe
        const parent = window.parent
        if (iframe) {
          iframe.height = ""
          const doc = iframe.contentDocument ? iframe.contentDocument : iframe.contentWindow.document
          const height = Math.max( doc.body.scrollHeight, doc.body.offsetHeight, doc.documentElement.clientHeight, doc.documentElement.scrollHeight, doc.documentElement.offsetHeight )
          iframe.height = height + "px"
          if (parent.setDemoFrameHeight) {
            parent.setDemoFrameHeight()
          }
        }
      }
    },
    beforeDestroy: function() {
      window.parent.removeEventListener('resize', this.setIFrameHeight)
    }
  }
</script>

// angular/demo/src/app/bootstrap/bootstrap.component.ts
import { Component, ViewChild, OnInit, AfterViewInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-bootstrap',
  templateUrl: './bootstrap.component.html',
  styleUrls: ['./bootstrap.component.css']
})
export class BootstrapComponent implements OnInit {
  @ViewChild('iframe') iframe;

  constructor() {
    this.setIFrameHeight = this.setIFrameHeight.bind(this)
  }

  ngOnInit() {
    window.parent.addEventListener('resize', this.setIFrameHeight);
  }

  ngOnDestroy() {
    window.parent.addEventListener('resize', this.setIFrameHeight);
  }

  setIFrameHeight(): void {
    const iframe = this.iframe && this.iframe.nativeElement;
    const parent = window.parent as any;
    if (iframe) {
      iframe.height = ""
      const doc = iframe.contentDocument ? iframe.contentDocument : iframe.contentWindow.document
      const height = Math.max( doc.body.scrollHeight, doc.body.offsetHeight )
      iframe.height = height + "px"
      if (parent.setDemoFrameHeight) {
        parent.setDemoFrameHeight()
      }
    }
  }
}

<div class="e-content">
  <iframe
    id="k-sink"
    class="border-0 w-100 align-top"
    title="Bootstrap 4 Kitchen Sink"
    src="../../../k-sink.html"
    #iframe
    (load)="setIFrameHeight()"
    style="min-height: 101vh; overflow: hidden;"></iframe>
</div>
