// angular/lib/components/select/examples/multiple/multiple.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import {IOption} from 'ng-select';

@Component({
  selector: 'select-multiple',
  encapsulation: ViewEncapsulation.None,
  template: `
    <e-select
      [options]="options"
      [(selected)]="selected"
      [multiple]="true"
      placeholder="Tags"></e-select>
  `
})
export class SelectMultipleComponent implements OnInit {
  public options: Array<IOption> = [
    {label: 'One', value: 'one'},
    {label: 'Two', value: 'two'},
    {label: 'Three', value: 'three'}
  ];

  selected: string[] = ['one'];

  constructor() { }

  ngOnInit() {
  }

}

// vue/example/lib/elements/components/select/examples/multiple.vue
<template>
  <e-select
    :multiple="true"
    :options="options"
    :value.sync="values"
    placeholder="Tags"
    ></e-select>
</template>

<script>
  import ESelect from '../index'

  export default {
    components: { ESelect },
    data: function() {
      return {
        options: ['One', 'Two', 'Three'],
        values: ['One']
      }
    }
  }
</script>
