// vue/demo/lib/elements/components/chart/examples/bar.vue
<template>
  <e-bar-chart
    :chartData="data"
    :height="height"
    :options="options"></e-bar-chart>
</template>

<script>
  import EBarChart from '../types/bar'
  import { colors } from '../options'

  export default {
    components: { EBarChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed'],
          datasets: [
            {
              label: 'Bar',
              backgroundColor: colors.green.string(),
              borderColor: '#ffffff',
              data: [7, 10, 13]
            }
          ]
        },
        options: {
          scales: {
            yAxes: [
              {
                ticks: {
                  beginAtZero: true
                }
              }
            ],
            xAxes: [
              {
                categoryPercentage: 0.6,
                barPercentage: 0.4,
              }
            ]
          },
        }
      }
    }
  }
</script>

// angular/demo/src/elements/components/chart/examples/bar/bar.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import colors from '../../colors'

@Component({
  selector: 'chart-bar',
  encapsulation: ViewEncapsulation.None,
  template: `
    <e-chart type="bar" [options]="options" [data]="data" [height]="height"></e-chart>
  `
})
export class ChartBarComponent implements OnInit {

  public options: any = {
    scales: {
      yAxes: [
        {
          ticks: {
            beginAtZero: true
          }
        }
      ],
      xAxes: [
        {
          categoryPercentage: 0.6,
          barPercentage: 0.4,
        }
      ]
    },
  }

  @Input() height: number;

  public data: any = {
    labels: ['Mon', 'Tue', 'Wed'],
    datasets: [
      {
        label: 'Bar',
        backgroundColor: colors.green.string(),
        borderColor: '#ffffff',
        data: [7, 10, 13]
      }
    ]
  }

  constructor() { }

  ngOnInit() {
  }

}
