// vue/demo/src/vue/pages/ProfileSettingsForm.vue
<template>
  <form
    class="form"
    @submit.prevent
    novalidate>
    <div class="row">
      <div class="col">
        <div class="row">
          <div class="col">
            <div class="form-group">
              <label>Full Name</label>
              <input class="form-control" type="text"
                name="name"
                v-model="data.name"
                :placeholder="user.name || 'Name'">
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label>Username</label>
              <input class="form-control" type="text"
                name="username"
                v-model="data.username"
                :placeholder="user.username || 'Username'">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <label>Email</label>
              <input class="form-control" type="text" placeholder="user@example.com">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col mb-3">
            <div class="form-group">
              <label>About</label>
              <textarea class="form-control" rows="5" placeholder="My Bio"></textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-sm-6 mb-3">
        <div class="mb-2">
          <b v-text="(isNew ? 'Account ' : 'Change ') + 'Password'"></b>
        </div>
        <div class="row" v-if="!isNew">
          <div class="col">
            <div class="form-group">
              <label>Current Password</label>
              <input class="form-control" type="password" placeholder="••••••">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <label v-text="(isNew ? '' : 'New ') + 'Password'"></label>
              <input class="form-control" type="password" placeholder="••••••">
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label>Confirm <span class="d-none d-xl-inline">Password</span></label>
              <input class="form-control" type="password" placeholder="••••••">
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-5 offset-sm-1 mb-3">
        <div class="mb-2">
          <b>Keeping in Touch</b>
        </div>
        <div class="row">
          <div class="col">
            <label>Email Notifications</label>
            <div class="custom-controls-stacked px-2">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" checked="checked" id="notifications-blog">
                <label class="custom-control-label" for="notifications-blog">Blog posts</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" checked="checked" id="notifications-news">
                <label class="custom-control-label" for="notifications-news">Newsletter</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" checked="checked" id="notifications-offers">
                <label class="custom-control-label" for="notifications-offers">Personal Offers</label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col d-flex justify-content-end">
        <button class="btn btn-primary" type="submit">Save Changes</button>
      </div>
    </div>
  </form>
</template>

<script>
  export default {
    props: {
      user: {
        type: Object,
        default: function() {
          return {
            name: '',
            username: '',
            date: 1
          }
        },
        validator: function(user) {
          var valid = typeof user.name === 'string' &&
                typeof user.username === 'string' &&
                typeof user.date === 'number';

          return valid
        }
      },
      isNew: {
        type: Boolean,
        default: false
      }
    },
    data: function() {
      return {
        data: Object.assign({}, this.user)
      }
    }
  }
</script>

// react/example/src/components/pages/ProfileSettingsForm.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

const propTypes = {
  data: PropTypes.object,
  isNew: PropTypes.bool
}

class ProfileSettingsForm extends Component {
  constructor(props) {
    super(props)
    this.handleSubmit = this.handleSubmit.bind(this)
    this.state = {
      data: Object.assign({}, props.data)
    }
  }

  handleSubmit(e) {
    e.preventDefault()
  }

  render() {
    return (
      <form
        className="form"
        onSubmit={this.handleSubmit}
        noValidate>
        <div className="row">
          <div className="col">
            <div className="row">
              <div className="col">
                <div className="form-group">
                  <label>Full Name</label>
                  <input className="form-control" type="text"
                    name="name"
                    defaultValue={this.state.data.name}
                    placeholder={this.state.data.name || 'Name'} />
                </div>
              </div>
              <div className="col">
                <div className="form-group">
                  <label>Username</label>
                  <input className="form-control" type="text"
                    name="username"
                    defaultValue={this.state.data.username}
                    placeholder={this.state.data.username || 'Username'} />
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col">
                <div className="form-group">
                  <label>Email</label>
                  <input className="form-control" type="text" placeholder="user@example.com" />
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col mb-3">
                <div className="form-group">
                  <label>About</label>
                  <textarea className="form-control" rows="5" placeholder="My Bio"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-12 col-sm-6 mb-3">
            <div className="mb-2">
              <b>{ (this.props.isNew ? 'Account ' : 'Change ') + 'Password' }</b>
            </div>
            {
              !this.props.isNew && (
                <div className="row">
                  <div className="col">
                    <div className="form-group">
                      <label>Current Password</label>
                      <input className="form-control" type="password" placeholder="••••••"/>
                    </div>
                  </div>
                </div>
              )
            }
            <div className="row">
              <div className="col">
                <div className="form-group">
                  <label>{ (this.props.isNew ? '' : 'New ') + 'Password' }</label>
                  <input className="form-control" type="password" placeholder="••••••" />
                </div>
              </div>
              <div className="col">
                <div className="form-group">
                  <label>Confirm <span className="d-none d-xl-inline">Password</span></label>
                  <input className="form-control" type="password" placeholder="••••••" />
                </div>
              </div>
            </div>
          </div>
          <div className="col-12 col-sm-5 offset-sm-1 mb-3">
            <div className="mb-2">
              <b>Keeping in Touch</b>
            </div>
            <div className="row">
              <div className="col">
                <label>Email Notifications</label>
                <div className="custom-controls-stacked px-2">
                  <div className="custom-control custom-checkbox">
                    <input type="checkbox" className="custom-control-input" defaultChecked={true} id="notifications-blog"/>
                    <label className="custom-control-label" htmlFor="notifications-blog">Blog posts</label>
                  </div>
                  <div className="custom-control custom-checkbox">
                    <input type="checkbox" className="custom-control-input" defaultChecked={true} id="notifications-news"/>
                    <label className="custom-control-label" htmlFor="notifications-news">Newsletter</label>
                  </div>
                  <div className="custom-control custom-checkbox">
                    <input type="checkbox" className="custom-control-input" defaultChecked={true} id="notifications-offers"/>
                    <label className="custom-control-label" htmlFor="notifications-offers">Personal Offers</label>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col d-flex justify-content-end">
            <button className="btn btn-primary" type="submit">Save Changes</button>
          </div>
        </div>
      </form>
    )
  }
}

ProfileSettingsForm.propTypes = propTypes

export default ProfileSettingsForm
