// react/demo/src/App.js
/* eslint-disable no-restricted-globals */
import React, { Component } from 'react'
import { Route, NavLink, Redirect, Switch } from 'react-router-dom'
import { UncontrolledDropdown as Dropdown, DropdownToggle, DropdownMenu } from 'reactstrap'

import Components from './components/Components'
import Pages from './components/Pages'
import Bootstrap from './components/Bootstrap'

import './demo.css'

class App extends Component {
  constructor(props) {
    super(props);

    this.togglePagesList = this.togglePagesList.bind(this);
    this.state = {
      pagesListOpen: false
    };
  }

  componentDidMount() {
    if (window === top) {
      document.body.setAttribute('style', '')
    }
  }

  togglePagesList(e) {
    e.preventDefault()
  }

  render() {
    return (
      <div>
        <div className="demo-tabs">
          <div className="container">
            <div className="px-sm-3">
              <ul className="nav nav-tabs flex-nowrap">
                <li className="nav-item position-relative">
                  <NavLink to="/pages" className="nav-link px-2 pr-3 px-sm-3 py-1 py-sm-2">
                    <span className="pr-2">Pages</span>
                  </NavLink>
                  <Dropdown className="demo-tabs-dropdown">
                    <DropdownToggle
                      className="my-1 my-sm-2 px-1"
                      onClick={(e) => { e.preventDefault() }}
                      tag="div"
                      caret></DropdownToggle>
                    <DropdownMenu>
                      <div className="dropdown-header">Pages List:</div>
                      <NavLink to="/pages/overview" className="dropdown-item">Overview</NavLink>
                      <NavLink to="/pages/users" className="dropdown-item">Users</NavLink>
                      <NavLink to="/pages/settings" className="dropdown-item">Profile</NavLink>
                    </DropdownMenu>
                  </Dropdown>
                </li>
                <li className="nav-item">
                  <NavLink to="/elements" className="nav-link px-2 px-sm-3 py-1 py-sm-2">Components</NavLink>
                </li>
                <li className="nav-item">
                  <NavLink to="/bootstrap" className="nav-link px-2 px-sm-3 py-1 py-sm-2">Bootstrap</NavLink>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div>
          <Switch>
            <Route path="/pages" component={Pages} base="/pages"/>
            <Route path="/elements" component={Components}/>
            <Route path="/bootstrap" component={Bootstrap}/>
            <Redirect from="/" to="/pages"/>
          </Switch>
        </div>
      </div>
    );
  }
}

export default App;

// angular/demo/src/app/app.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent implements OnInit {
  ngOnInit() {
    if (window == top) {
      document.body.setAttribute('style', '')
    }
  }
}

<div class="app-wrapper">
  <div class="app-tabs">
    <div class="container">
      <div class="px-sm-3">
        <ul class="nav nav-tabs flex-nowrap">
          <li class="nav-item position-relative">
            <a routerLink="/pages" routerLinkActive="active" class="nav-link px-2 px-sm-3 pr-3 py-1 py-sm-2">
              <span class="pr-2">Pages</span>
            </a>
            <div class="demo-tabs-dropdown" ngbDropdown>
              <div class="my-1 my-sm-2 p-0 px-1 caret" ngbDropdownToggle></div>
              <div ngbDropdownMenu>
                <div class="dropdown-header">Pages List:</div>
                <a routerLink="/pages/overview" routerLinkActive="active" class="dropdown-item">Overview</a>
                <a routerLink="/pages/users" routerLinkActive="active" class="dropdown-item">Users</a>
                <a routerLink="/pages/settings" routerLinkActive="active" class="dropdown-item">Profile</a>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a routerLink="/components" routerLinkActive="active" class="nav-link px-2 px-sm-3 py-1 py-sm-2">Components</a>
          </li>
          <li class="nav-item">
            <a routerLink="/bootstrap" routerLinkActive="active" class="nav-link px-2 px-sm-3 py-1 py-sm-2">Bootstrap</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div>
    <router-outlet></router-outlet>
  </div>
</div>
