// vue/demo/lib/elements/components/select/examples/single.vue
<template>
  <e-select
    :options="options"
    :value.sync="value"
    placeholder="Single"
    ></e-select>
</template>

<script>
  import ESelect from '../index'

  export default {
    components: { ESelect },
    data: function() {
      return {
        options: ['One', 'Two', 'Three'],
        value: 'One'
      }
    }
  }
</script>

// react/testing/src/elements/components/select/examples/Single.js
import React, { Component } from 'react'
import ESelect from '../index'

class ESelectSingle extends Component {
  constructor(props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
    this.state = {
      selected: null
    }
  }

  handleChange(option) {
    this.setState({
      selected: option
    })
  }

  render() {
    const options = [
      { value: 1, label: 'One' },
      { value: 2, label: 'Two' },
      { value: 3, label: 'Three' }
    ]

    return (
      <ESelect
        value={this.state.selected}
        options={options}
        onChange={this.handleChange}
        placeholder="Single"
      />
    )
  }
}

export default ESelectSingle
