// react/testing/src/components/pages/include/Sidebar.js
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import ENavlist from '../../../elements/components/navlist'

class Sidebar extends Component {
  render() {
    return (
      <div className="col-12 col-lg-auto mb-3" style={{ width: '200px'}}>
        <div className="card p-3">
          <ENavlist activeBg>
            <ul className="nav">
              <li className="nav-item">
                <NavLink to="/pages/overview" className="nav-link px-2">
                  <i className="fa fa-fw fa-bar-chart mr-1"></i>
                  <span>Dashboard</span>
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink to="/pages/users" className="nav-link px-2">
                  <i className="fa fa-fw fa-clone mr-1"></i>
                  <span>Users</span>
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink to="/pages/settings" className="nav-link px-2">
                  <i className="fa fa-fw fa-cog mr-1"></i>
                  <span>Settings</span>
                </NavLink>
              </li>
            </ul>
          </ENavlist>
        </div>
      </div>
    )
  }
}

export default Sidebar

// vue/testing/src/components/pages/include/Sidebar.vue
<template>
  <div class="e-sidebar col-12 col-lg-auto mb-3">
    <slot>
      <div class="card p-3">
        <e-navlist active-bg>
          <ul class="nav">
            <li class="nav-item">
              <router-link to="/pages/overview" class="nav-link px-2">
                <i class="fa fa-fw fa-bar-chart mr-1"></i>
                <span>Overview</span>
              </router-link>
            </li>
            <li class="nav-item">
              <router-link to="/pages/users" class="nav-link px-2">
                <i class="fa fa-fw fa-clone mr-1"></i>
                <span>CRUD</span>
              </router-link>
            </li>
            <li class="nav-item">
              <router-link to="/pages/settings" class="nav-link px-2">
                <i class="fa fa-fw fa-cog mr-1"></i>
                <span>Settings</span>
              </router-link>
            </li>
          </ul>
        </e-navlist>
      </div>
    </slot>
    <slot name="nested"></slot>
  </div>
</template>

<script>
  import ENavlist from 'elements/navlist'

  export default {
    components: { ENavlist }
  }
</script>

<style lang="scss">
  .e-sidebar {
    width: 200px;
  }
</style>
