// vue/testing/lib/elements/components/chart/examples/radar.vue
<template>
  <e-radar-chart
    :chartData="data"
    :height="height"
    :options="options"></e-radar-chart>
</template>

<script>
  import ERadarChart from '../types/radar'
  import { colors } from '../options'

  export default {
    components: { ERadarChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
          datasets: [
            {
              label: 'Radar',
              borderColor: colors.green.opaquer(0.1).string(),
              backgroundColor: colors.green.fade(0.3).string(),
              data: [12.5, 12.5, 12.5, 12.5, 12.5, 12.5]
            }
          ]
        },
        options: {
          legend: {
            display: false
          },
          scale: {
            ticks: {
              beginAtZero: true
            }
          }
        }
      }
    }
  }
</script>

// react/example/src/elements/components/chart/examples/Radar.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class ERadarChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      legend: {
        display: false
      },
      scale: {
        ticks: {
          beginAtZero: true
        }
      }
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        datasets: [
          {
            label: 'Radar',
            borderColor: colors.green.alpha(0.9).string(),
            backgroundColor: colors.green.alpha(0.5).string(),
            data: [12.5, 12.5, 12.5, 12.5, 12.5, 12.5]
          }
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="radar" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default ERadarChart
