// vue/example/lib/elements/components/navline/examples/default.vue
<template>
  <div class="card px-2">
    <e-navline>
      <ul class="nav">
        <li class="nav-item active">
          <a href="" class="nav-link" @click.prevent>
            <span>Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="" class="nav-link" @click.prevent>
            <span>Bookmarks</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="" class="nav-link" @click.prevent>
            <span>Messages</span>
          </a>
        </li>
      </ul>
    </e-navline>
  </div>
</template>

<script>
  import ENavline from '../index'

  export default {
    components: { ENavline }
  }
</script>

// react/testing/src/elements/components/navline/examples/Default.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ENavline from '../index'
import { Nav, NavItem, NavLink } from 'reactstrap'

const propTypes = {
  className: PropTypes.string
}

class ENavlineDefault extends Component {
  render() {
    return (
      <div className="card px-2">
        <ENavline>
          <Nav>
            <NavItem>
              <NavLink className="active" href="" onClick={(e) => e.preventDefault()}>Home</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>Bookmarks</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>Messages</NavLink>
            </NavItem>
          </Nav>
        </ENavline>
      </div>
    );
  }
}

ENavlineDefault.propTypes = propTypes

export default ENavlineDefault
