// vue/example/lib/elements/components/chart/examples/donut.vue
<template>
  <e-donut-chart
    :chartData="data"
    :options="options"
    :height="height"></e-donut-chart>
</template>

<script>
  import EDonutChart from '../types/donut'
  import { colors } from '../options'

  export default {
    components: { EDonutChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed'],
          datasets: [
            {
              label: 'Donut',
              backgroundColor: colors.array(),
              hoverBorderColor: '#fff',
              data: [5, 10, 8]
            }
          ]
        },
        options: {
          legend: {
            position: 'bottom',
            labels: {
              usePointStyle: true,
              padding: 20
            }
          }
        }
      }
    }
  }
</script>

// angular/demo/src/elements/components/chart/examples/donut/donut.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import colors from '../../colors'

@Component({
  selector: 'chart-donut',
  encapsulation: ViewEncapsulation.None,
  template: `
    <e-chart type="doughnut" [options]="options" [data]="data" [height]="height"></e-chart>
  `
})
export class ChartDonutComponent implements OnInit {

  public options: any = {
    legend: {
      position: 'bottom',
      labels: {
        usePointStyle: true,
        padding: 20
      }
    }
  }

  @Input() height: number;

  public data: any = {
    labels: ['Mon', 'Tue', 'Wed'],
    datasets: [
      {
        label: 'Donut',
        backgroundColor: colors.array(),
        hoverBorderColor: '#fff',
        data: [5, 10, 8]
      }
    ]
  }

  constructor() { }

  ngOnInit() {
  }

}
