// react/testing/src/elements/components/select/examples/Single.js
import React, { Component } from 'react'
import ESelect from '../index'

class ESelectSingle extends Component {
  constructor(props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
    this.state = {
      selected: null
    }
  }

  handleChange(option) {
    this.setState({
      selected: option
    })
  }

  render() {
    const options = [
      { value: 1, label: 'One' },
      { value: 2, label: 'Two' },
      { value: 3, label: 'Three' }
    ]

    return (
      <ESelect
        value={this.state.selected}
        options={options}
        onChange={this.handleChange}
        placeholder="Single"
      />
    )
  }
}

export default ESelectSingle

// angular/demo/src/elements/components/select/examples/single/single.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import {IOption} from 'ng-select';

@Component({
  selector: 'select-single',
  encapsulation: ViewEncapsulation.None,
  template: `
    <e-select [options]="options" [(selected)]="selected" placeholder="Select"></e-select>
  `
})
export class SelectSingleComponent implements OnInit {
  public options: Array<IOption> = [
    {label: 'One', value: 'one'},
    {label: 'Two', value: 'two'},
    {label: 'Three', value: 'three'}
  ];

  selected: string;

  constructor() { }

  ngOnInit() {
  }

}
