// vue/testing/src/components/pages/include/Navbar.vue
<template>
  <e-navbar class="my-3 px-lg-4" :title="'Dashboard'">
    <div slot="brand">
      <router-link to="/pages/overview" class="e-logo mx-4">
        <span>Elements <small>stay simple</small></span>
      </router-link>
    </div>

    <div slot="collapse">
      <ul class="navbar-nav pt-3 pt-md-0">
        <li class="nav-item">
          <router-link to="/pages/overview" class="nav-link">Overview</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/pages/users" class="nav-link">CRUD</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/pages/settings" class="nav-link">Settings</router-link>
        </li>
      </ul>
    </div>

    <div slot="actions">
      <router-link to="/pages/settings" class="btn btn-success d-md-none">
        <i class="fa fa-user-circle"></i>
      </router-link>
      <div class="btn-group d-none d-md-block">
        <a href="#" class="btn btn-success" @click.prevent>
          <i class="fa fa-bell"></i>
        </a>
        <router-link to="/pages/settings" class="btn btn-success">
          <span class="mx-1">John Smith</span>
        </router-link>
      </div>
    </div>
  </e-navbar>
</template>

<script>
  import ENavbar from 'elements/navbar'

  export default {
    components: { ENavbar }
  }
</script>

<style lang="scss"></style>

// react/example/src/components/pages/include/Navbar.js
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import ENavbar from '../../../elements/components/navbar'

class Navbar extends Component {
  render() {
    const Brand = () => (
      <NavLink className="e-logo mx-4" to="/pages/overview">
        <span>Elements <small>stay simple</small></span>
      </NavLink>
    )
    const CollapseNav = () => (
      <ul className="navbar-nav pt-3 pt-md-0">
        <li className="nav-item">
          <NavLink className="nav-link" to="/pages/overview">Overview</NavLink>
        </li>
        <li className="nav-item">
          <NavLink className="nav-link" to="/pages/users">CRUD</NavLink>
        </li>
        <li className="nav-item">
          <NavLink className="nav-link" to="/pages/settings">Settings</NavLink>
        </li>
      </ul>
    )
    const Actions = () => (
      <div>
        <NavLink to="/pages/settings" className="btn btn-success d-md-none">
          <i className="fa fa-user-circle"></i>
        </NavLink>
        <div className="btn-group d-none d-md-block">
          <button className="btn btn-success">
            <i className="fa fa-bell"></i>
          </button>
          <NavLink to="/pages/settings" className="btn btn-success">
            <span className="mx-1">John Smith</span>
          </NavLink>
        </div>
      </div>
    )

    return (
      <ENavbar
        className="my-3 px-lg-4"
        title="Overview"
        brandNode={<Brand/>}
        collapseNode={<CollapseNav/>}
        actionsNode={<Actions/>} />
    )
  }
}

export default Navbar
