// vue/example/lib/elements/components/select/examples/multiple.vue
<template>
  <e-select
    :multiple="true"
    :options="options"
    :value.sync="values"
    placeholder="Tags"
    ></e-select>
</template>

<script>
  import ESelect from '../index'

  export default {
    components: { ESelect },
    data: function() {
      return {
        options: ['One', 'Two', 'Three'],
        values: ['One']
      }
    }
  }
</script>

// react/example/src/elements/components/select/examples/Multiple.js
import React, { Component } from 'react'
import ESelect from '../index'

class ESelectMultiple extends Component {
  constructor(props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
    this.state = {
      selected: [
        { value: 1, label: 'One' }
      ]
    }
  }

  handleChange(option) {
    this.setState({
      selected: option
    })
  }

  render() {
    const options = [
      { value: 1, label: 'One' },
      { value: 2, label: 'Two' },
      { value: 3, label: 'Three' }
    ]

    return (
      <ESelect
        value={this.state.selected}
        options={options}
        onChange={this.handleChange}
        isMulti={true}
        placeholder="Multiple"/>
    )
  }
}

export default ESelectMultiple
