// vue/example/lib/elements/components/panel/examples/login-form.vue
<template>
  <e-panel>
    <template slot="title">
      <div class="h6 text-center w-100 mb-2">Sign In / Login</div>
    </template>
    <form>
      <div class="form-group">
        <input type="email" class="form-control" placeholder="Email">
      </div>
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Password">
      </div>
      <div class="form-group d-flex justify-content-between align-items-center">
        <a href="#" class="text-muted btn btn-link" @click.prevent>Need Help?</a>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      <div class="form-group text-center m-0">
        <div class="btn-group">
          <button type="button" class="btn btn-outline-secondary">
            <i class="fa fa-fw fa-twitter"></i>
          </button>
          <button type="button" class="btn btn-outline-secondary">
            <i class="fa fa-fw fa-facebook"></i>
          </button>
          <button type="button" class="btn btn-outline-secondary">
            <i class="fa fa-fw fa-github"></i>
          </button>
        </div>
      </div>
    </form>
  </e-panel>
</template>

<script>
  import EPanel from '../index'

  export default {
    components: { EPanel },
    data: function() {
      return {}
    }
  }
</script>

// angular/example/src/elements/components/panel/examples/login-form/login-form.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'panel-login-form',
  templateUrl: './login-form.component.html',
  encapsulation: ViewEncapsulation.None
})
export class PanelLoginFormComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<e-panel>
  <div class="w-100" title>
    <div class="h6 text-center w-100 mb-2">Sign In / Login</div>
  </div>
  <form (submit)="$event.preventDefault()">
    <div class="form-group">
      <input type="email" class="form-control" placeholder="Email">
    </div>
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Password">
    </div>
    <div class="form-group d-flex justify-content-between align-items-center">
      <a href="" class="text-muted btn btn-link" (click)="$event.preventDefault()">Need Help?</a>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <div class="form-group text-center m-0">
      <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary">
          <i class="fa fa-fw fa-twitter"></i>
        </button>
        <button type="button" class="btn btn-outline-secondary">
          <i class="fa fa-fw fa-facebook"></i>
        </button>
        <button type="button" class="btn btn-outline-secondary">
          <i class="fa fa-fw fa-github"></i>
        </button>
      </div>
    </div>
  </form>
</e-panel>
