// angular/example/src/app/pages/layouts/default/default.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'layout-default',
  templateUrl: './default.component.html',
  styleUrls: ['./default.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class LayoutDefaultComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <div class="e-content">
    <div class="row">
      <div class="col">
        <app-navbar></app-navbar>
      </div>
    </div>
    <div class="row flex-lg-nowrap">
      <div class="d-none d-lg-block">
        <app-sidebar>
          <ng-content select="[sidebar]"></ng-content>
        </app-sidebar>
      </div>
      <div class="col">
        <ng-content></ng-content>
      </div>
    </div>
  </div>
</div>

// react/demo/src/components/pages/layouts/Default.js
import React, { Component } from 'react'
import Navbar from '../include/Navbar'
import Sidebar from '../include/Sidebar'

class DefaultLayout extends Component {
  render() {
    return (
      <div className="container">
        <div className="e-content">
          <div className="row">
            <div className="col">
              <Navbar/>
            </div>
          </div>
          <div className="row flex-lg-nowrap">
            <Sidebar className="d-none d-lg-block"/>
            <div className="col">
              { this.props.children }
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default DefaultLayout
