// vue/demo/lib/elements/components/datepicker/types/inline/index.vue
<template>
  <flat-pickr class="d-none" :config="options" :value.sync="date"></flat-pickr>
</template>

<script>
  import EDatepicker from '../../index'

  export default {
    extends: EDatepicker,
    data: function() {
      return {
        localDefaults: {
          inline: true
        }
      }
    }
  }
</script>

// react/example/src/elements/components/datepicker/types/inline/index.js
import React from 'react'
import Flatpickr from 'react-flatpickr'
import EDatepicker from '../../index'

class EDatepickerInline extends EDatepicker {
  constructor(props) {
    super(props)
    this.localDefaults = {
      inline: true
    }
  }

  render() {
    return (
      <Flatpickr
        className="d-none"
        value={this.state.dates}
        options={this.options}
        onChange={this.handleDateChange}></Flatpickr>
    )
  }
}

export default EDatepickerInline
