// vue/demo/lib/elements/components/datepicker/types/addons/index.vue
<template>
  <div class="input-group">
    <span v-if="prepend" class="input-group-prepend">
      <span class="input-group-text">
        <i :class="prepend"></i>
      </span>
    </span>
    <flat-pickr
      class="form-control"
      ref="picker"
      :value="date"
      :config="options"
      :placeholder="placeholder"
      @on-change="handleDateChange"></flat-pickr>
    <div v-if="clear && isDate" class="input-group-append">
      <button class="btn btn-outline-secondary" type="button" @click="clearDate">
        <i class="fa fa-close"></i>
      </button>
    </div>
    <span v-if="append" class="input-group-append">
      <span class="input-group-text">
        <i :class="append"></i>
      </span>
    </span>
  </div>
</template>

<script>
  import EDatepicker from '../../index'

  export default {
    extends: EDatepicker,
    props: {
      prepend: {
        type: String,
        default: ''
      },
      append: {
        type: String,
        default: ''
      },
      clear: {
        type: Boolean,
        default: false
      }
    },
    data: function() {
      return {
        localDefaults: {
          wrap: true
        }
      }
    },
    methods: {
      clearDate: function() {
        this.$refs.picker.fp.clear()
      }
    }
  }
</script>

// react/example/src/elements/components/datepicker/types/addons/index.js
import React from 'react'
import PropTypes from 'prop-types'
import Flatpickr from 'react-flatpickr'
import EDatepicker from '../../index'

const propTypes = {
  prepend: PropTypes.string,
  append: PropTypes.string,
  clear: PropTypes.bool
}

class EDatepickerAddons extends EDatepicker {
  constructor(props) {
    super(props)
    this.clearDate = this.clearDate.bind(this)
    this.localDefaults = {}
  }

  clearDate() {
    this.picker.flatpickr.clear()
  }

  render() {
    const Prepend = () => (
      <span className="input-group-prepend">
        <span className="input-group-text">
          <i className={this.props.prepend}></i>
        </span>
      </span>
    )

    const Append = () => (
      <span className="input-group-append">
        <span className="input-group-text">
          <i className={this.props.append}></i>
        </span>
      </span>
    )

    const Clear = () => (
      <div className="input-group-append">
        <button className="btn btn-outline-secondary" type="button" onClick={this.clearDate}>
          <i className="fa fa-close"></i>
        </button>
      </div>
    )

    return (
      <div className="input-group">
        { this.props.prepend && <Prepend/> }
        <Flatpickr
          className="form-control"
          ref={(input) => { this.picker = input}}
          value={this.state.dates}
          options={this.options}
          placeholder={this.props.placeholder}
          onChange={this.handleDateChange}/>
        { this.props.clear && this.state.dates.length > 0 && <Clear/> }
        { this.props.append && <Append/> }
      </div>
    )
  }
}

EDatepickerAddons.propTypes = propTypes

export default EDatepickerAddons
