// react/demo/src/elements/components/table/examples/advanced-table/index.js
import React, { Component } from 'react'
import classNames from 'classnames'
import Moment from 'moment'
import { UncontrolledDropdown as Dropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap'
import ENavlist from '../../../navlist'
import ETable from '../../index'

import './advanced-table.css'

class AdvancedTable extends Component {
  constructor(props) {
    super(props)
    this.handlePageChange = this.handlePageChange.bind(this)
    this.handleFilterChange = this.handleFilterChange.bind(this)
    this.state = {
      page: 1,
      perPage: 5,
      items: items.slice(),
      tab: 'all',
      filters: {
        search: '',
        active: false
      }
    }
  }


  handlePageChange(page, perPage) {
    if (page !== this.state.page || perPage !== this.state.perPage) {
      this.setState({
        page,
        perPage
      })
    }
  }

  handleFilterChange(filter, value) {
    const filterName = String(filter)
    if (this.state.filters.hasOwnProperty(filterName) && value !== this.state.filters[filterName]) {
      this.setState({
        filters: Object.assign({}, this.state.filters, {
          [filterName]: value
        })
      })
    }
  }

  updateItem(id, updatedFields = {}) {
    const items = this.state.items.slice(),
          item = items.find((i) => i.id === id),
          index = items.indexOf(item)

    if (index > -1) {
      this.setState({
        items: [
          ...items.slice(0, index),
          Object.assign({}, item, updatedFields),
          ...items.slice(index + 1),
        ]
      })
    }
  }

  handleSelect(id, selected) {
    this.updateItem(id, { selected })
  }

  handleSelectAll(checked) {
    const items = this.state.items.slice()
    this.setState({
      items: items.map(item => Object.assign({}, item, { selected: checked }))
    })
  }

  handleTabClick(tab, e) {
    e.preventDefault()
    if (String(tab)) {
      this.setState({
        tab: String(tab)
      })
    }
  }

  toggleBookmark(id, bookmark) {
    this.updateItem(id, { bookmark })
  }

  render() {
    const columns = [
      {
        dataField: 'selected',
        text: '',
        headerClasses: 'align-top',
        headerFormatter: (column, index) => (
          <div className="custom-control custom-control-inline custom-control-nameless custom-checkbox m-0">
            <input
              type="checkbox"
              className="custom-control-input"
              id="all-items"
              checked={tabs[this.state.tab].length === tabs.selected.length }
              onChange={(e) => this.handleSelectAll(e.target.checked)} />
            <label className="custom-control-label" htmlFor="all-items"></label>
          </div>
        ),
        formatter: (selected, row, index) => (
          <div className="custom-control custom-control-inline custom-checkbox custom-control-nameless m-0">
            <input
              type="checkbox"
              className="custom-control-input"
              id={'item-' + row.id}
              checked={selected ? true : false}
              onChange={(e) => this.handleSelect(row.id, e.target.checked)} />
            <label className="custom-control-label" htmlFor={'item-' + row.id}></label>
          </div>
        )
      },
      {
        dataField: 'name',
        text: 'Name',
        headerClasses: 'max-width',
        classes: 'text-nowrap'
      },
      {
        dataField: 'date',
        text: 'Date',
        classes: 'text-nowrap',
        sort: true,
        formatter: (cell, row, index) => (
          <span>{ Moment.unix(cell).format('DD MMM YYYY') }</span>
        )
      },
      {
        dataField: 'status',
        text: 'Status',
        classes: 'text-center',
        formatter: (cell, row, index) => (
          <span className={classNames('badge', cell ? 'badge-light' : 'badge-secondary')}>{ String(cell) }</span>
        )
      },
      {
        dataField: 'bookmark',
        text: ' ',
        classes: 'text-center',
        formatter: (cell, row, index) => (
          <span className={classNames('e-advanced-table__bookmark', { active: row.bookmark })}>
            <i className="fa fa-bookmark fa-fw" onClick={() => this.toggleBookmark(row.id, !row.bookmark)}></i>
          </span>
        )
      }
    ]

    const tabs = function() {
      let all = this.state.items.slice()

      if (this.state.filters.search) {
        all = searchArray(all, this.state.filters.search, ['name'])
      }
      if (this.state.filters.active) {
        all = all.filter(item => item.status)
      }

      return {
        all,
        bookmarks: all.filter(i => i.bookmark),
        selected: all.filter(i => i.selected)
      }
    }.bind(this)()

    return (
      <div className="card">
        <div className="card-body">
          <div className="e-advanced-table">
            <div className="d-flex mb-3">
              <div className="mr-3 e-advanced-table__search-input">
                <form className="form-inline">
                  <div className="input-with-ico w-100">
                    <i className="input-ico fa fa-fw fa-search"></i>
                    <div className="input-group flex-nowrap w-100">
                      <input
                        className="form-control w-100"
                        type="search"
                        placeholder="Search"
                        value={this.state.filters.search}
                        onChange={(e) => this.handleFilterChange('search', e.target.value)}/>
                      {
                        this.state.filters.search.length > 0 && (
                          <span className="input-group-append">
                            <button className="btn btn-secondary" type="button" onClick={() => this.handleFilterChange('search', '')}>
                              <i className="fa fa-times"></i>
                            </button>
                          </span>
                        )
                      }
                    </div>
                  </div>
                </form>
              </div>
              <div className="">
                <Dropdown group>
                  <button className="btn btn-success">
                    <i className="fa fa-plus"></i>
                    <span className="d-none d-md-inline-block ml-1">Create</span>
                  </button>
                  <DropdownToggle caret color="success" />
                  <DropdownMenu right>
                    <DropdownItem header>With selected:</DropdownItem>
                    <DropdownItem>Remove</DropdownItem>
                    <DropdownItem divider/>
                    <DropdownItem header>Toggle:</DropdownItem>
                    <DropdownItem>Status</DropdownItem>
                    <DropdownItem>Bookmark</DropdownItem>
                  </DropdownMenu>
                </Dropdown>
              </div>
            </div>
            <div className="row flex-lg-nowrap">
              <div className="col">
                <ENavlist activeBold>
                  <ul className="nav">
                    {
                      Object.keys(tabs).map((tab, index) => (
                        <li className={classNames('nav-item', { active: this.state.tab === tab })} key={index}>
                          <a href="" className="nav-link" onClick={(e) => this.handleTabClick(tab, e)}>
                            <span>{ tab.charAt(0).toUpperCase() + tab.slice(1) }</span>&nbsp;
                            <small>/&nbsp;{ tabs[tab].length }</small>
                          </a>
                        </li>
                      ))
                    }
                  </ul>
                </ENavlist>
                <hr className="mb-3"/>
                <div className="px-2">
                  <div className="custom-control custom-checkbox m-0">
                    <input
                      type="checkbox"
                      className="custom-control-input"
                      id="actives-check"
                      checked={this.state.filters.active}
                      onChange={(e) => this.handleFilterChange('active', e.target.checked)} />
                    <label className="custom-control-label" htmlFor="actives-check">Actives Only</label>
                  </div>
                </div>
                <hr className="my-3 d-md-none"/>
              </div>
              <div className="col-12 col-md-9">
                <ETable
                  keyField='id'
                  data={ tabs[this.state.tab] }
                  columns={ columns }
                  pagination={{
                    page: this.state.page,
                    sizePerPage: this.state.perPage,
                    onPageChange: this.handlePageChange
                  }} />
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

const items = [
  { id: 1,  name: 'Adam Cotter',       date: 1512792908, status: true,  bookmark: false },
  { id: 2,  name: 'Pauline Noble',     date: 1516977768, status: false, bookmark: true,  selected: true },
  { id: 3,  name: 'Sherilyn Metzel',   date: 1517042476, status: true,  bookmark: false, selected: true },
  { id: 4,  name: 'Terrie Boaler',     date: 1516439865, status: true,  bookmark: false },
  { id: 5,  name: 'Rutter Pude',       date: 1515850922, status: false, bookmark: true  },
  { id: 6,  name: 'Clifford Benjamin', date: 1516898701, status: true,  bookmark: false },
  { id: 7,  name: 'Thedric Romans',    date: 1515707885, status: false, bookmark: true  },
  { id: 8,  name: 'Haily Carthew',     date: 1517056707, status: true,  bookmark: false },
  { id: 9,  name: 'Dorothea Joicey',   date: 1513090469, status: true,  bookmark: false },
  { id: 10, name: 'Mikaela Pinel',     date: 1512892304, status: false, bookmark: true  },
  { id: 11, name: 'Donnell Farries',   date: 1512299369, status: true,  bookmark: false },
  { id: 12, name: 'Letizia Puncher',   date: 1512769349, status: false, bookmark: true  },
  { id: 13, name: 'Kania Yallowley',   date: 1515521487, status: true,  bookmark: false },
  { id: 14, name: 'Clay De Francesco', date: 1515012234, status: false, bookmark: true  },
  { id: 15, name: 'Ina Queree',        date: 1514458367, status: false, bookmark: true  },
  { id: 16, name: 'Rasia Awty',        date: 1516943842, status: false, bookmark: true  },
  { id: 17, name: 'Basil Crosham',     date: 1512108299, status: true,  bookmark: false },
  { id: 18, name: 'Alexis Dodworth',   date: 1516814115, status: false, bookmark: true  },
  { id: 19, name: 'Greg Onyon',        date: 1517071308, status: true,  bookmark: false },
  { id: 20, name: 'Barry Carbett',     date: 1515450742, status: true,  bookmark: false },
  { id: 21, name: 'Carlyle Adran',     date: 1512498261, status: true,  bookmark: false },
  { id: 22, name: 'Guillaume Petel',   date: 1512742913, status: false, bookmark: true  },
  { id: 23, name: 'Wendeline Glasner', date: 1513319267, status: false, bookmark: true  },
  { id: 24, name: 'Sylvia Petrollo',   date: 1516080489, status: false, bookmark: true  },
  { id: 25, name: 'Meade Quoit',       date: 1513972299, status: true,  bookmark: false },
  { id: 26, name: 'Eugine Planke',     date: 1515488407, status: false, bookmark: true  },
  { id: 27, name: 'Thoma Drakeley',    date: 1515023660, status: false, bookmark: true  },
  { id: 28, name: 'Web Margetson',     date: 1513557231, status: true,  bookmark: false },
  { id: 29, name: 'Erskine Stivens',   date: 1515233788, status: true,  bookmark: false },
  { id: 30, name: 'Jedidiah Emmer',    date: 1512614842, status: false, bookmark: true  },
  { id: 31, name: 'Wolfie Drakers',    date: 1512381522, status: false, bookmark: true  },
  { id: 32, name: 'Allie Quiney',      date: 1515488202, status: true,  bookmark: false }
]

// filters the given array of objects with a provided text and fields
function searchArray(array, query, fields = []) {
  if (!array.length || !String(query)) {
    return array
  }

  return array.filter(item => {
    let found = false;
    for (let key in item) {
      if (fields.length && fields.indexOf(key) < 0) {
        continue
      }
      if (typeof item[key] === 'string' &&
          item[key].toLowerCase().indexOf(query.toLowerCase()) >= 0) {
        found = true;
      }
    }
    return found;
  })
}

export default AdvancedTable

// vue/example/lib/elements/components/table/examples/advanced-table.vue
<template>
  <div class="card">
    <div class="card-body">
      <div class="e-advanced-table">
        <div class="d-flex mb-3">
          <div class="mr-3 e-advanced-table__search-input">
            <form class="form-inline">
              <div class="input-with-ico w-100">
                <i class="input-ico fa fa-fw fa-search"></i>
                <div class="input-group flex-nowrap w-100">
                  <input class="form-control w-100" type="search" v-model="filters.search" placeholder="Search" aria-label="Search">
                  <span v-if="filters.search.length" class="input-group-append">
                    <button class="btn btn-secondary" type="button" @click="clearSearch()">
                      <i class="fa fa-times"></i>
                    </button>
                  </span>
                </div>
              </div>
            </form>
          </div>
          <div class="">
            <b-dropdown variant="success" split right>
              <template slot="button-content">
                <span>
                  <i class="fa fa-plus"></i>
                  <span class="d-none d-md-inline-block ml-1">Create</span>
                </span>
              </template>
              <h6 class="dropdown-header">With selected:</h6>
              <a class="dropdown-item" href="#" @click.prevent>Remove</a>
              <div class="dropdown-divider"></div>
              <h6 class="dropdown-header">Toggle:</h6>
              <a class="dropdown-item" href="#" @click.prevent>Status</a>
              <a class="dropdown-item" href="#" @click.prevent>Bookmark</a>
            </b-dropdown>
          </div>
        </div>
        <div class="row flex-lg-nowrap">
          <div class="col">
            <e-navlist active-bold>
              <ul class="nav">
                <li class="nav-item" :class="{ active: tab == 'all' }">
                  <a href="" class="nav-link" @click.prevent="tab = 'all'">
                    <span>All</span>
                    <small>/ {{ all.length }}</small>
                  </a>
                </li>
                <li class="nav-item" :class="{ active: tab == 'bookmarks' }">
                  <a href="" class="nav-link" @click.prevent="tab = 'bookmarks'">
                    <span>Bookmarks</span>
                    <small>/ {{ bookmarks.length }}</small>
                  </a>
                </li>
                <li class="nav-item" :class="{ active: tab == 'selected' }">
                  <a href="" class="nav-link" @click.prevent="tab = 'selected'">
                    <span>Selected</span>
                    <small>/ {{ selected.length }}</small>
                  </a>
                </li>
              </ul>
            </e-navlist>
            <hr class="mb-3">
            <div class="px-2">
              <label class="custom-control custom-checkbox m-0">
                <input type="checkbox" class="custom-control-input" id="actives-check" v-model="filters.actives">
                <span class="custom-control-label" for="actives-check">Actives Only</span>
              </label>
            </div>
            <hr class="my-3 d-md-none">
          </div>
          <div class="col-12 col-md-9">
            <b-table class="fa-sort-icons table-rounded mb-0"
              :items="display"
              :fields="fields"
              :per-page="perPage"
              :current-page="currentPage"
              show-empty
              responsive
              bordered>
              <template slot="HEAD_check" slot-scope="data">
                <div @click.stop class="custom-control custom-control-inline custom-control-nameless custom-checkbox m-0 align-top">
                  <input type="checkbox" class="custom-control-input" v-model="selectedAll" :id="'item-'+data.key">
                  <label class="custom-control-label" :for="'item-'+data.key"></label>
                </div>
              </template>
              <template slot="check" slot-scope="data">
                <div class="custom-control custom-control-inline custom-control-nameless custom-checkbox m-0 align-top">
                  <input type="checkbox" class="custom-control-input" @click.stop :value="data.item" v-model="selectedItems" :id="'item-'+data.index">
                  <label class="custom-control-label" :for="'item-'+data.index"></label>
                </div>
              </template>
              <template slot="date" slot-scope="data">
                <span>{{ data.item.date | moment('DD MMM YYYY') }}</span>
              </template>
              <template slot="status" slot-scope="data">
                <span class="badge" :class="data.value ? 'badge-light' : 'badge-secondary'">{{ data.value }}</span>
              </template>
              <template slot="bookmark" slot-scope="data">
                <span class="e-advanced-table__bookmark" :class="{ active: data.item.bookmark }">
                  <i class="fa fa-bookmark fa-fw" @click.stop="data.item.bookmark = !data.item.bookmark"></i>
                </span>
              </template>
            </b-table>
            <b-pagination v-if="display.length > perPage" class="pagination-separated m-0 mt-3" size="sm" align="center" :total-rows="display.length" :per-page="perPage" v-model="currentPage" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import ENavlist from '../../navlist'

  const items = [
    { name: 'Adam Cotter',       date: 1512792908, status: true,  bookmark: true  },
    { name: 'Pauline Noble',     date: 1516977768, status: false, bookmark: true  },
    { name: 'Sherilyn Metzel',   date: 1517042476, status: true,  bookmark: false },
    { name: 'Terrie Boaler',     date: 1516439865, status: true,  bookmark: false },
    { name: 'Rutter Pude',       date: 1515850922, status: false, bookmark: false },
    { name: 'Clifford Benjamin', date: 1516898701, status: true,  bookmark: false },
    { name: 'Thedric Romans',    date: 1515707885, status: false, bookmark: false },
    { name: 'Haily Carthew',     date: 1517056707, status: true,  bookmark: true  },
    { name: 'Dorothea Joicey',   date: 1513090469, status: true,  bookmark: false },
    { name: 'Mikaela Pinel',     date: 1512892304, status: false, bookmark: false },
    { name: 'Donnell Farries',   date: 1512299369, status: true,  bookmark: false },
    { name: 'Letizia Puncher',   date: 1512769349, status: false, bookmark: false },
    { name: 'Kania Yallowley',   date: 1515521487, status: true,  bookmark: false },
    { name: 'Clay De Francesco', date: 1515012234, status: false, bookmark: true  },
    { name: 'Ina Queree',        date: 1514458367, status: false, bookmark: false },
    { name: 'Rasia Awty',        date: 1516943842, status: false, bookmark: false },
    { name: 'Basil Crosham',     date: 1512108299, status: true,  bookmark: false },
    { name: 'Alexis Dodworth',   date: 1516814115, status: false, bookmark: true  },
    { name: 'Greg Onyon',        date: 1517071308, status: true,  bookmark: false },
    { name: 'Barry Carbett',     date: 1515450742, status: true,  bookmark: false },
    { name: 'Carlyle Adran',     date: 1512498261, status: true,  bookmark: false },
    { name: 'Guillaume Petel',   date: 1512742913, status: false, bookmark: true  },
    { name: 'Wendeline Glasner', date: 1513319267, status: false, bookmark: false },
    { name: 'Sylvia Petrollo',   date: 1516080489, status: false, bookmark: false },
    { name: 'Meade Quoit',       date: 1513972299, status: true,  bookmark: true  },
    { name: 'Eugine Planke',     date: 1515488407, status: false, bookmark: false },
    { name: 'Thoma Drakeley',    date: 1515023660, status: false, bookmark: false },
    { name: 'Web Margetson',     date: 1513557231, status: true,  bookmark: false },
    { name: 'Erskine Stivens',   date: 1515233788, status: true,  bookmark: true  },
    { name: 'Jedidiah Emmer',    date: 1512614842, status: false, bookmark: false },
    { name: 'Wolfie Drakers',    date: 1512381522, status: false, bookmark: false },
    { name: 'Allie Quiney',      date: 1515488202, status: true,  bookmark: false }
  ]

  const fields = [
    { key: 'check' },
    { key: 'name', sortable: true, thClass: 'max-width', tdClass: 'text-nowrap' },
    { key: 'date', sortable: true, tdClass: 'text-nowrap' },
    { key: 'status', tdClass: 'text-center align-middle' },
    { key: 'bookmark', label: ' ', tdClass: 'align-middle' },
  ]

  // filters the given array of objects with a provided text and fields
  const searchArray = function(array, query, fields = []) {
    if (!array.length || !String(query)) {
      return array
    }

    return array.filter(item => {
      let found = false;
      for (let key in item) {
        if (fields.length && fields.indexOf(key) < 0) {
          continue
        }
        if (typeof item[key] == 'string' &&
            item[key].toLowerCase().indexOf(query.toLowerCase()) >= 0) {
          found = true;
        }
      }
      return found;
    })
  }

  export default {
    components: { ENavlist },
    data: function() {
      return {
        items,
        fields,
        currentPage: 1,
        perPage: 5,
        tab: 'all',
        filters: {
          search: '',
          actives: false,
        },
        selectedItems: []
      }
    },
    computed: {
      all: function() {
        let items = this.items;

        if (this.filters.search) {
          items = searchArray(this.items, this.filters.search, ['name'])
        }

        if (this.filters.actives) {
          items = items.filter(i => i.status)
        }

        return items
      },
      bookmarks: function() {
        return this.all.filter(i => i.bookmark)
      },
      selected: function() {
        return this.all.filter(i => this.selectedItems.indexOf(i) > -1)
      },
      selectedAll: {
        get: function() {
          return this.display.length && this.display.every(i => this.selected.indexOf(i) > -1)
        },
        set: function(value) {
          if (value) {
            this.selectedItems = [...this.display]
          } else {
            this.selectedItems = this.selectedItems.filter(i => this.display.indexOf(i) < 0)
          }
        }
      },
      display: function() {
        return this[this.tab] || []
      }
    },
    methods: {
      clearSearch: function() {
        this.filters.search = ''
      }
    }
  }
</script>

<style lang="scss">
  @import "../../../scss/bootstrap/variables";

  .e-advanced-table {
    &__search-input {
      -webkit-box-flex: 1;
      -ms-flex-positive: 1;
      flex-grow: 1;
    }

    &__bookmark {
      cursor: pointer;
      color: $gray-200;

      &:hover,
      &.active {
        color: map-get($theme-colors, "secondary");
      }
    }
  }
</style>
