// vue/lib/components/chart/examples/pie.vue
<template>
  <e-pie-chart
    :chartData="data"
    :options="options"
    :height="height"></e-pie-chart>
</template>

<script>
  import EPieChart from '../types/pie'
  import { colors } from '../options'

  export default {
    components: { EPieChart },
    props: {
      height: {
        type: Number
      }
    },
    data: function() {
      return {
        data: {
          labels: ['Mon', 'Tue', 'Wed'],
          datasets: [
            {
              label: 'Pie',
              backgroundColor: colors.array(),
              hoverBorderColor: '#fff',
              data: [5, 10, 8]
            }
          ]
        },
        options: {
          legend: {
            position: 'bottom',
            labels: {
              usePointStyle: true,
              padding: 20
            }
          }
        }
      }
    }
  }
</script>

// react/demo/src/elements/components/chart/examples/Pie.js
import React, { Component } from 'react'
import { colors } from '../options'
import EChart from '../index'

class EPieChart extends Component {
  constructor(props) {
    super(props)
    this.options = {
      legend: {
        position: 'bottom',
        labels: {
          usePointStyle: true,
          padding: 20
        }
      }
    }
    this.state = {
      data: {
        labels: ['Mon', 'Tue', 'Wed'],
        datasets: [
          {
            label: 'Pie',
            backgroundColor: colors.array(),
            hoverBorderColor: '#fff',
            data: [5, 10, 8]
          }
        ]
      }
    }
  }

  render() {
    return (
      <EChart type="pie" data={this.state.data} options={this.options} {...this.props}/>
    )
  }
}

export default EPieChart
