// react/demo/src/elements/components/navlist/examples/ActiveBold.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ENavlist from '../index'
import { Nav, NavItem, NavLink } from 'reactstrap'

const propTypes = {
  className: PropTypes.string
}

class ENavlistActiveBold extends Component {
  render() {
    return (
      <div className="card p-3">
        <ENavlist activeBold>
          <Nav>
            <NavItem>
              <NavLink className="active" href="" onClick={(e) => e.preventDefault()}>Home</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>Bookmarks</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>Messages</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="" onClick={(e) => e.preventDefault()}>Settings</NavLink>
            </NavItem>
          </Nav>
        </ENavlist>
      </div>
    );
  }
}

ENavlistActiveBold.propTypes = propTypes

export default ENavlistActiveBold

// vue/lib/components/navlist/examples/active-bold.vue
<template>
  <div class="card p-3">
    <e-navlist active-bold>
      <ul class="nav">
        <li class="nav-item active">
          <a href="" class="nav-link" @click.prevent>
            <span>Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="" class="nav-link" @click.prevent>
            <span>Bookmarks</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="" class="nav-link" @click.prevent>
            <span>Messages</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="" class="nav-link" @click.prevent>
            <span>Settings</span>
          </a>
        </li>
      </ul>
    </e-navlist>
  </div>
</template>

<script>
  import ENavlist from '../index'

  export default {
    components: { ENavlist }
  }
</script>
